export const SESSION_TOKEN_MAX_AGE_SECONDS = 15 * 60;
export const REFRESH_TOKEN_MAX_AGE_SECONDS = 30 * 24 * 60 * 60;

export const SESSION_TOKEN_LENGTH = 32;

export const SESSION_DURATION_MS = SESSION_TOKEN_MAX_AGE_SECONDS * 1000;
export const REFRESH_DURATION_DAYS = 30;

export const DEVICE_NAME_MAX_LENGTH = 50;
export const IP_ADDRESS_MAX_LENGTH = 50;
