export const DEFAULT_NANOID_LENGTH = 21;

export const USER_ID_LENGTH = DEFAULT_NANOID_LENGTH;
export const SESSION_ID_LENGTH = DEFAULT_NANOID_LENGTH;
export const FILE_ID_LENGTH = DEFAULT_NANOID_LENGTH;
export const UPLOAD_SESSION_ID_LENGTH = DEFAULT_NANOID_LENGTH;
