export const TRASH_RETENTION_DAYS = 30;
export const TRASH_RETENTION_MS = TRASH_RETENTION_DAYS * 24 * 60 * 60 * 1000;

export const TRASH_PURGE_BATCH_SIZE = 50;
export const STALE_UPLOAD_CLEANUP_BATCH_SIZE = 50;
