import { BYTES_PER_GIGABYTE, BYTES_PER_MEGABYTE } from "./bytes";

export const UPLOAD_CHUNK_SIZE_BYTES = 5 * BYTES_PER_MEGABYTE;
export const MAX_UPLOAD_SIZE_BYTES = 100 * BYTES_PER_MEGABYTE;
export const DEFAULT_STORAGE_QUOTA_BYTES = BYTES_PER_GIGABYTE;
export const UPLOAD_SESSION_EXPIRY_HOURS = 24;
export const UPLOAD_SESSION_EXPIRY_MS = UPLOAD_SESSION_EXPIRY_HOURS * 60 * 60 * 1000;
export const UPLOAD_INIT_LOCK_TIMEOUT_SECONDS = 5;
export const PENDING_FILE_MIME_TYPE = "application/octet-stream";
